backend:
  name: github
  repo: ShevtsovAndrey/Media
  branch: main
  auth_type: implicit
  client_id: Ov23lic7FhjBNL3GIDgc
  
site_url: https://shevtsovandrey.github.io/Media
display_url: https://shevtsovandrey.github.io/Media

media_folder: "assets/img"
public_folder: "/assets/img"

collections:
  - name: "gallery"
    label: "Gallery"
    folder: "data"
    create: true
    format: "json"
    extension: "json"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Photo", name: "image", widget: "image" }