backend:
  name: github
  repo: ShevtsovAndrey/Media
  branch: main

media_folder: "assets/img"
public_folder: "/assets/img"

collections:
  - name: "gallery"
    label: "Gallery"
    folder: "data"
    create: true
    format: "json"
    extension: "json"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Photo", name: "image", widget: "image" }